### ISSUE TITLE
Random problems with switches and sensors

### ISSUE THREAD

**Issue by Enterich3000** [Mimiix/node-red-contrib-deconz#113]
** Describe issue **
Hey Dudes, since last week i've got the problem that the plugin didn't get any signals from sensors and switches, randomly.

For Example, i'll get it when I open the Deconz-gui and reboot my raspberry, after that nodered will not get any feedback from the switches for hours!
Mostly on the next day it works again fine.

Secound example: I'm just pairing a new lamp and reboot my pi to get all changes in homebridge and deconz. All lamps are working fine, but not sensors and switches.

BTW: Homebridge gets the signals from switches and sensors, but very delayed.. about 5 secs later...

I don't have any idea whrere the problem can be...

Ahh, and fourthermore: All Button actions in deconz itself also running fine!

-> so maybe there's a problem in my REST-API i'm not recognizing..

** Hardware / Software **
  - raspberry 4B+
  - version of deconz gateway: [2.07.01 / 8.12.2020] 
  - version of node-red-contrib-deconz: [1.20]

**Comment by Zehir** [comment]
The node-red and deconz are both host on you raspberry ?
Are you using home-assistant ?

**Comment by Enterich3000** [comment]
Hey Folks,

i got it.. about one week later.
It is a major problem in deconz (that’s because they released raspbee II) - the time zone just changed in deconz but not on my pi and Homebridge for example.

changing the timezone in Deconz fixed the issue immediately.

Greetz
