### ISSUE TITLE
How to send a command to start a configured Scene?

### ISSUE THREAD

**Issue by nicedevil007** [Mimiix/node-red-contrib-deconz#46]
Hey andrey,

it's me again :D I just found out that I can configure cool Scenes inside the Phoscon App. Your Deconz Nodes discover these scenes but I can't find out how to start such a scene?

Can you help out again?
Thank you!

**Comment by andreypopov** [comment]
Choose scene from list, send "true"

**Comment by nicedevil007** [comment]
Oh wow... I'm doing everything with the json object after my last issue here :) I never read through the other options...

But how can I select the right scene if I coded more than one scene inside Conbee stick?

Is there also a possibility to send the scene with a json object?

**Comment by nicedevil007** [comment]
Just found an other already closed issue where a guy posted a screen of the selection of the scene by itself:

![image](https://user-images.githubusercontent.com/17103076/71321562-3ed74100-24bb-11ea-94de-3a4ebc85438b.png)

So this answered the question of how I can choose a specific scene. 

Now the only missing answer is: Is it possible to set this up by an json object like bri, hue, sat and so on?

**Comment by andreypopov** [comment]
try 1, 2 ,3 - id of the scene
{scene:1}

**Comment by andreypopov** [comment]
any news here?

**Comment by nicedevil007** [comment]
Hey andrey, was a bit busy over the last days. 
Will test it as soon as I got a bit time today or this weekend :) 
Thank you so far!

**Comment by nicedevil007** [comment]
Hey andrey, tryed this and also used "on": true for testing. Unfurtunately it won't change anything.
There is no error in the debug window.

My injection node sends a message like this:
![image](https://user-images.githubusercontent.com/17103076/72384812-7930a880-371e-11ea-8056-f7f604169a82.png)

The deconz node looks like this:
![image](https://user-images.githubusercontent.com/17103076/72384840-89488800-371e-11ea-880f-32c77ef3e27c.png)

**Comment by Zehir** [comment]
This is an old issue, if your problem is not solved please open it again. Thanks
