### ISSUE TITLE
Error messages in the log

### ISSUE THREAD

**Issue by Schmello** [Mimiix/node-red-contrib-deconz#50]
`Dec 26 13:06:44 Homematic daemon.err node-red: Encountered an error while controlling device
Dec 26 13:06:44 Homematic daemon.err node-red: Error(1) was:
Dec 26 13:06:44 Homematic daemon.err node-red: undefined
Dec 26 13:06:44 Homematic daemon.err node-red: (node:12645) UnhandledPromiseRejectionWarning: [object Array]
Dec 26 13:06:44 Homematic daemon.err node-red: (node:12645) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 193)`

** Hardware / Software **
  - Deconz Synology Docker 
  - raspberry 2 (Node Red)
  - version of deconz gateway: [2.05.69 / 06/09/2019]
  - version of node-red-contrib-deconz: [1.1.9]

**Comment by Zehir** [comment]
This is an old issue, if your problem is not solved please open it again. Thanks
