### ISSUE TITLE
Battery Node missing state as with Deconz-in

### ISSUE THREAD

**Issue by Schmello** [Mimiix/node-red-contrib-deconz#51]
With Deconz-in it is possible to choose a state at output 1.
This option is missing on the Deconz-Battery. Output 1 is not used.
Is it possible to add state output 1 with the Deconz Battery?

**Comment by andreypopov** [comment]
as I know, not possible
deconz sends battery status only after an hour

**Comment by Schmello** [comment]
is it not possible to add the state option for output 1?
Then only one status would be sent every hour similar to the Deconz-in node.
A value is easier to use in NodeRed.
Example window contact (True False)

**Comment by Zehir** [comment]
This is an old issue, if your problem is not solved please open it again. Thanks
