### ISSUE TITLE
missing temperature on Vibration and Waterleak senzors

### ISSUE THREAD

**Issue by elpaso666** [Mimiix/node-red-contrib-deconz#53]
Hello,

in Phoscon app I see temperature values for both Vibration senzor and Water leak senzor. Would it be possible to add them?

thx
Jakub

**Comment by andreypopov** [comment]
can you show me complete msg from these sensors?

**Comment by andreypopov** [comment]
deconz sends temperature with battery sensor, once in hour, sometime value is missing

**Comment by elpaso666** [comment]
here is the msg, tigether with Phoscon screenshot


{"payload":false,"payload_raw":{"config":{"battery":100,"on":true,"reachable":true,"temperature":2300},"ep":1,"etag":"8cc616032a0cad87a71a0937a694e0cc","manufacturername":"LUMI","modelid":"lumi.sensor_wleak.aq1","name":"WS1 - Sklep","state":{"lastupdated":"2020-01-14T10:38:33","lowbattery":false,"tampered":false,"water":false},"swversion":"20170721","type":"ZHAWater","uniqueid":"00:15:8d:00:02:11:b4:b2-01-0500","device_type":"sensors","device_id":6},"meta":{"config":{"battery":100,"on":true,"reachable":true,"temperature":2300},"ep":1,"etag":"8cc616032a0cad87a71a0937a694e0cc","manufacturername":"LUMI","modelid":"lumi.sensor_wleak.aq1","name":"WS1 - Sklep","state":{"lastupdated":"2020-01-14T10:38:33","lowbattery":false,"tampered":false,"water":false},"swversion":"20170721","type":"ZHAWater","uniqueid":"00:15:8d:00:02:11:b4:b2-01-0500","device_type":"sensors","device_id":6},"_msgid":"979ec64f.ae2118"}

![image](https://user-images.githubusercontent.com/7722883/72341596-efa3bb00-36ca-11ea-87e8-33b0d87b856a.png)

**Comment by andreypopov** [comment]
so, you can catch temperature from battery node? right?

**Comment by elpaso666** [comment]
actually, you are very right and I am very blind. It is located in **msg.meta.config.temperature**

I believe same will be somewhere in msg for vibration sensor, I will check if it is also there.

I understand it is not very needed, but would be nice to have it as parameter directly in the contrib, ale for other users.

I though that not all the info is passed over in msg. but obviously it is!

**Comment by Zehir** [comment]
This issue seems to be resolved, if not please open it again. Thanks
