### ISSUE TITLE
interval between Xiaomi double click

### ISSUE THREAD

**Issue by elpaso666** [Mimiix/node-red-contrib-deconz#62]
Hi,

I have found out, that for unknown reason there must be 3-5s delay between repeating double-click (code 1004).

Single click 1002 does not suffer with this.

Same if I do double-single-double then internal is also not needed and all messages are sent right away. however with 1004 right next to the 1st one, 2nd is not not send.

tested with debug node on simple Deconz-IN.

thx
Jakub

**Comment by andreypopov** [comment]
what button do you use?
I use aqara round button - works great even with 4-click, 5-click.

**Comment by elpaso666** [comment]
from phoscon:
Vendor Xiaomi
Product Smart Switch WXKG01LM

it was working fine in my previous Xiaomi GW implementation, so button are sending the command most probably there is a problem on Deconz/Phoscon side?

**Comment by andreypopov** [comment]
I dont know. try to change battery :)

**Comment by elpaso666** [comment]
I have 8 buttons, all are doing the same... it is basically needed to do single to be able to receive another double right a way...

**Comment by andreypopov** [comment]
resolved?

**Comment by elpaso666** [comment]
Hi,
actually not :( sometimes it works... but 100% double is only after single click... all buttons are the same. worked before on xiaomi GW and linux based bridge

which exaclty buttons you are using? as I have also no triple click

**Comment by andreypopov** [comment]
xiaomi round button
aqara opple

**Comment by Zehir** [comment]
This is a device related issue, you can talk about it on the Deconz Discord server, you will get more help there : https://discord.gg/dt4wcDjuNH
