### ISSUE TITLE
Get Settings, IP issues during autenticate app?

### ISSUE THREAD

**Issue by bramv101** [Mimiix/node-red-contrib-deconz#69]
Phoscon GW at ip 172.30.xx.xx-, while HA exist at 192.168.xx.xx

Running HassOS 3.12, installed deconz as explained, dongle is coming through without problem, devices are coming through without a problem.
However when launching web UI, i see GW with 192.168.xx ip, once logged in it shows top right an ip with 172.30.xx.xx, which in itself is not a problem yet when trying to connect NodeRed, i get problems.

I go in the the gateway and do authenticate app for 60 seconds, yet NodeRed refuses to connect when i fill in either of above ip adresses and try to get settings as instructed

**Comment by Zehir** [comment]
This is an old issue, if your problem is not solved please open it again. Thanks
In your case you have to set the HA ip address and click Get Settings. Also make sure that you enabled the forwarding of ports in deconz settings inside HA Supervisor.
