### ISSUE TITLE
Device not set message

### ISSUE THREAD

**Issue by chrisg2003** [Mimiix/node-red-contrib-deconz#70]
** Describe issue **
The nodes show a red square with Device not set message.
Although it seems to be working ok, no messages are sent at flow deploy.
Potentially I am miss-using the node.

[{"id":"313a13d3.a690cc","type":"ui_gauge","z":"51c3c794.573698","name":"","group":"ed1cde5a.65a3b","order":1,"width":"6","height":"4","gtype":"gage","title":"Hot press Humidity","label":"%","format":"{{msg.payload.humidity/100}}","min":0,"max":"100","colors":["#00b500","#e6e600","#ca3838"],"seg1":"","seg2":"","x":610,"y":220,"wires":[]},{"id":"929753c5.63457","type":"deconz-get","z":"51c3c794.573698","name":"","server":"58ac5871.b966b8","device":"00:15:8d:00:04:23:70:6a-01-0405","device_name":"LanT1 : ZHAHumidity","state":"0","x":340,"y":240,"wires":[["313a13d3.a690cc","bd4da80b.a89938"]]},{"id":"aa4f9a5a.a40ec8","type":"inject","z":"51c3c794.573698","name":"","topic":"","payload":"","payloadType":"date","repeat":"3600","crontab":"","once":true,"onceDelay":0.1,"x":130,"y":240,"wires":[["929753c5.63457"]]},{"id":"7d927bbe.0c74e4","type":"deconz-get","z":"51c3c794.573698","name":"","server":"58ac5871.b966b8","device":"00:15:8d:00:04:23:70:6a-01-0402","device_name":"LanT1 : ZHATemperature","state":"0","x":350,"y":120,"wires":[["f5b3df66.432c9"]]},{"id":"71a6043a.74667c","type":"inject","z":"51c3c794.573698","name":"","topic":"","payload":"","payloadType":"date","repeat":"900","crontab":"","once":true,"onceDelay":0.1,"x":130,"y":120,"wires":[["7d927bbe.0c74e4"]]},{"id":"33badc7f.e99114","type":"ui_gauge","z":"51c3c794.573698","name":"","group":"ed1cde5a.65a3b","order":2,"width":"6","height":"4","gtype":"gage","title":"Hot Press temperature","label":"Deg. C","format":"{{msg.payload}}","min":0,"max":"40","colors":["#00b500","#e6e600","#ca3838"],"seg1":"23","seg2":"30","x":860,"y":80,"wires":[]},{"id":"7515506e.9e3d","type":"ui_chart","z":"51c3c794.573698","name":"","group":"ed1cde5a.65a3b","order":7,"width":0,"height":0,"label":"Hot Press temp. graph","chartType":"line","legend":"false","xformat":"dd HH:mm","interpolate":"linear","nodata":"","dot":false,"ymin":"0","ymax":"40","removeOlder":"48","removeOlderPoints":"","removeOlderUnit":"3600","cutout":0,"useOneColor":false,"colors":["#1f77b4","#aec7e8","#ff7f0e","#2ca02c","#98df8a","#d62728","#ff9896","#9467bd","#c5b0d5"],"useOldStyle":false,"outputs":1,"x":860,"y":120,"wires":[[]]},{"id":"f5b3df66.432c9","type":"function","z":"51c3c794.573698","name":"Scale Max Min","func":"var dstr = Date().toString();\nvar payload;\nvar msg2 = {};\nvar msg3 = {};\nvar max = global.get(\"LanT1Max\",\"File\")|| 0;\nvar min = global.get(\"LanT1Min\",\"File\")|| 100;\nmsg2.payload = \"Updated - \"+ dstr.substr(0,24);\nnew flow.set(\"LastUpHP\",msg2.payload,\"File\");\npayload = msg.payload.temperature;\npayload = payload/100;\nif (payload > max){\n    max = payload;\n}\nif (payload < min){\n    min = payload;\n}\nmsg3.payload = \"Temperature Max = \" + max + \" Min = \" + min;\nglobal.set(\"LanT1Max\",max,\"File\");\nglobal.set(\"LanT1Min\",min,\"File\");\nmsg.payload = payload;\nreturn [msg, msg2, msg3];","outputs":3,"noerr":0,"x":580,"y":120,"wires":[["33badc7f.e99114","7515506e.9e3d"],["c9e656db.fa1e98"],["1e8c3169.f4988f"]]},{"id":"bd4da80b.a89938","type":"ui_text","z":"51c3c794.573698","group":"ed1cde5a.65a3b","order":6,"width":"6","height":"1","name":"","label":"Hot Press Battery percentage","format":"{{msg.meta.config.battery}}","layout":"row-spread","x":650,"y":260,"wires":[]},{"id":"c9e656db.fa1e98","type":"ui_text","z":"51c3c794.573698","group":"ed1cde5a.65a3b","order":3,"width":0,"height":0,"name":"Hot Press","label":"","format":"{{msg.payload}}","layout":"row-spread","x":820,"y":160,"wires":[]},{"id":"1e8c3169.f4988f","type":"ui_text","z":"51c3c794.573698","group":"ed1cde5a.65a3b","order":4,"width":0,"height":0,"name":"HP MaxMin","label":"","format":"{{msg.payload}}","layout":"row-left","x":830,"y":200,"wires":[]},{"id":"6057a15d.faa8b","type":"ui_button","z":"51c3c794.573698","name":"Reset HP max min","group":"ed1cde5a.65a3b","order":5,"width":0,"height":0,"passthru":false,"label":"Reset Max/Mins","tooltip":"","color":"","bgcolor":"","icon":"","payload":"true","payloadType":"str","topic":"","x":130,"y":180,"wires":[["62b60bc5.b488f4"]]},{"id":"62b60bc5.b488f4","type":"function","z":"51c3c794.573698","name":"Scale Max Min","func":"var payload = msg.payload;\nif (payload === \"true\"){\n   global.set(\"LanT1Max\",0,\"File\");\n   global.set(\"LanT1Min\",100,\"File\");   \n    return msg;\n}\n\n","outputs":1,"noerr":0,"x":340,"y":180,"wires":[["7d927bbe.0c74e4"]]},{"id":"ed1cde5a.65a3b","type":"ui_group","z":"","name":"Sensors","tab":"80a65695.491a28","order":2,"disp":true,"width":"6","collapse":false},{"id":"58ac5871.b966b8","type":"deconz-server","z":"","name":"Phoscon-GW","ip":"192.168.86.32","port":"80","apikey":"FF949D1257","ws_port":"443","secure":false,"polling":"15"},{"id":"80a65695.491a28","type":"ui_tab","z":"","name":"Environment","icon":"dashboard","order":2,"disabled":false,"hidden":false}]
Export your flow in json 

** Screens / Logs **

![image](https://user-images.githubusercontent.com/61418252/76963281-afee8f00-6918-11ea-88cc-43164d9112d4.png)
** Hardware / Software **
  - raspberry 3 
  - version of deconz gateway: [2.05.74 / ? 
  - version of node-red-contrib-deconz: [1.1.13]

**Comment by Zehir** [comment]
This is an old issue, if your problem is not solved please open it again. Thanks
