### ISSUE TITLE
Can't setup server node

### ISSUE THREAD

**Issue by jov58** [Mimiix/node-red-contrib-deconz#74]
I have an RPi 4 with Home Assistant, deCONZ and node-red in Docker (homeassistant/raspberrypi4-homeassistant:stable, marthoc/deconz, nodered/node-red:latest).

deCONZ is working (webport 8080, websocket port default so 443), Phoscon is working and I can use deCONZ switches in Home Assistant. In node-red I use node-red-contrib-home-assistant-websocket to connect to Home Assistant without problem.

So everything seems OK for node-red-contrib-deconz (1.1.13). However, when I click _Get Settings_ when adding a new deconz-server config node it returns _Can't disover your device, enter settings manually_.

I can't figure out what's going on here.
Any ideas anyone?

**Comment by andreypopov** [comment]
I dont know, check settings
![2020-04-06_20-09-56](https://user-images.githubusercontent.com/1624839/78585486-a59e2180-7842-11ea-93eb-262153be243b.png)

**Comment by jov58** [comment]
OK, but where do I check those? Looks like a Home Assistant card, but I don't recognize it. I use Home Assistant Core with the standard deCONZ integration, not hass.io.

**Comment by jov58** [comment]
For the standard integration of deCONZ in Home Assistant Core you don't need anything in configuration.yaml. But to be sure I restarted HA after adding this to configuration.yaml:

```
deconz:
  host: <ip-address>
  port: 8080
```

But I still get the same error. I also use node-red-contrib-home-assistant-websocket btw. But does this message have anything to do with HA? I thought that if you try to add a deconz-server node, node-red connects directly to deconz, with or without HA.

![Annotation 2020-04-07 215058](https://user-images.githubusercontent.com/33156488/78713263-4a3f6280-791a-11ea-9dec-ae32a1a2eeaa.png)

**Comment by flonair** [comment]
> I dont know, check settings
> ![2020-04-06_20-09-56](https://user-images.githubusercontent.com/1624839/78585486-a59e2180-7842-11ea-93eb-262153be243b.png)

Had the same problem, but this solved it! :-)

**Comment by Zehir** [comment]
You have to set the home assistant ip address and click on Get Settings
