### ISSUE TITLE
Brightness Step Up / Down

### ISSUE THREAD

**Issue by peterguy04** [Mimiix/node-red-contrib-deconz#84]
not sure if this can already be done but i couldnt find it.

Add the ability to Step up and Down the brightness to create a dimming function as a default option in the `OUT` node. i am currently using the HTTP request node to PUT 
```{"bri_inc": -25}```  with values ranging -255 to 255

**Comment by der-pw** [comment]
Thanks for the tip!
Works as well with a simple object. Same with "ct_inc".
![image](https://user-images.githubusercontent.com/44023915/98485681-6260c280-2218-11eb-98bc-70f500edfcc2.png)

**Comment by Zehir** [comment]
`bri_inc` is only for [Windows cover](https://dresden-elektronik.github.io/deconz-rest-doc/endpoints/lights/#window-covering-parameters) and it's deprecated.
You can use a get node and do some maths.

**Comment by der-pw** [comment]
Ah, thanks for the hint!
Hmm, the get-node delays the feedback. That's how I had it at first and it definitely felt slower to me.

**Comment by Zehir** [comment]
On the in node he already do a request like the get to get more data on the event. But you dont have the choice to do this

**Comment by der-pw** [comment]
Okay, I understand. The get-node is triggered by my event.
Maybe I got it mixed up
In first tests, it works so fast like the bri_inc as well.  thanks! ;)

**Comment by Zehir** [comment]
I test, it's takes around 5ms to do the get request from another computer in WiFi so I don't think you can reduce this delay with my idea to store the current value of the brightness inside node red and update it with events too.

**Comment by Zehir** [comment]
> `bri_inc` is only for [Windows cover](https://dresden-elektronik.github.io/deconz-rest-doc/endpoints/lights/#window-covering-parameters) and it's deprecated.
> You can use a get node and do some maths.

@der-pw I want to change my answer, bri_inc is not deprecated. The doc on deconz website is outdated, you can check the [phillips hue api](https://developers.meethue.com/develop/hue-api/lights-api/#get-attr-and-state), they are verry similar, you will need an free account. The `bri_inc` return the new `bri` value but for now you are not able to get it but this will change in 2.0

**Comment by der-pw** [comment]
Thank you @Zehir for the detailed answer.
I am happy that bri_inc is not going to expire.
