### ISSUE TITLE
Server setup problem

### ISSUE THREAD

**Issue by Albertowue** [Mimiix/node-red-contrib-deconz#88]
I have problems connecting Node-RED deconz-nodes to zigbee sensors via ConBee II.
In Node-RED deconz:
IP-address: 127.0.0.1 or localhost or core-deconz or homeassistantip (I use Hassio on RP3)
Port: 40850 or blank
Websocket port: 8081 or blank

Clicked on ‘Get Settings’

And the only thing I get is the alert ‘HomeAssistant? Fill only IP-address of your HA server’

In the Deconz Network setting I set port 40850 and 8081 like the image in the home...reboot the sistem many many time...

What am I doing wrong?

Node-RED addon version 7.2
node-red-contrib-deconz version 1.2
Home Assistant version 114.3

Alberto

**Comment by RealKanashii** [comment]
Hi, I had the same problem until now. 

To configure the Conf node use:
Name: "DeConz"
IP-Address: 192.168.xxx.xxx (The address you see in the top right corner of the Phoscon app)
Port: 80
Websocket: 80
SSL: no

Save everything and  deploy node red. You will see the red dot in the node disappear (showing it connected). 
Now return to the conf node and try to recover the Key. If it fails you have to recover it manually.


If you cannot recover the API key do this:
- Install a REST plugin for chrome like Talend API Tester
- Use the command "POST"
- The URL is (use your own IP):  http://192.168.xxx.xxx:80/api
- The body of the request is:
`{ "devicetype" : "Node Red"}`
- You will get something like:  { "username" : " XXXXXXX" } 
- The XXXXXX is your API key.

**Comment by Zehir** [comment]
You still have the issue @Albertowue ?

**Comment by Albertowue** [comment]
Problem solved with this procedure, thanks 😀
