### ISSUE TITLE
Store API Key in node-red credentials area

### ISSUE THREAD

**Issue by DDDanny** [Mimiix/node-red-contrib-deconz#94]
Great Stuff, works like a charm in my small setup.

_One security issue/improvement: As node-red has a secure encrypted credential store only readable on the device instance with provided secret key and the API-key is a credential ;)_

**To avoid key traveling unsecured in exports/backups I strongly advice that the API-Key in gateway-config is switched to a node-red pwd field input, that is encrypted during exports.**
like is the mysql or email-node does

current example of a export:
`....{"id":"e01xxxx.f0478","type":"deconz-server","z":"","name":"gatewayname","ip":"127.0.0.1","port":"1234","apikey":"<API KEY IN PLAIN TEXT>","ws_port":"12345","secure":false,"polling":"15"}]`

Remark: Of course this is a hard change affecting all user who upgrade :-(

**Comment by Zehir** [comment]
Will in the next release
