### ISSUE TITLE
IKEA colour light: hue value ignored

### ISSUE THREAD

**Issue by TheNON75** [Mimiix/node-red-contrib-deconz#95]
** Describe issue **
Zigbee device: IKEA TRADFRI bulb E14 CWS opal 600lm light
When changing colour in Phoscon app, the hue value on the "in node" are not changing (both outputs)
When a new hue value is sent to the out node, nothing happens 

thanks in advance for having a look at it

** Your flow here **
[{"id":"cddc535b.d59c8","type":"homekit-service","z":"ba820b55.5a5b68","g":"c4b69ca4.39948","isParent":true,"bridge":"8140d8f9.95c11","parentService":"","name":"Blume Light","serviceName":"Lightbulb","topic":"","filter":false,"manufacturer":"NRCHKB","model":"1.2.0","serialNo":"Default Serial Number","firmwareRev":"1.2.0","hardwareRev":"1.2.0","softwareRev":"1.2.0","cameraConfigVideoProcessor":"ffmpeg","cameraConfigSource":"","cameraConfigStillImageSource":"","cameraConfigMaxStreams":2,"cameraConfigMaxWidth":1280,"cameraConfigMaxHeight":720,"cameraConfigMaxFPS":10,"cameraConfigMaxBitrate":300,"cameraConfigVideoCodec":"libx264","cameraConfigAudioCodec":"libfdk_aac","cameraConfigAudio":false,"cameraConfigPacketSize":1316,"cameraConfigVerticalFlip":false,"cameraConfigHorizontalFlip":false,"cameraConfigMapVideo":"0:0","cameraConfigMapAudio":"0:1","cameraConfigVideoFilter":"scale=1280:720","cameraConfigAdditionalCommandLine":"-tune zerolatency","cameraConfigDebug":false,"cameraConfigSnapshotOutput":"disabled","cameraConfigInterfaceName":"","characteristicProperties":"{\"Brightness\":true,\"Hue\":true,\"Saturation\":true}","waitForSetupMsg":false,"outputs":2,"x":510,"y":680,"wires":[["ddd64464.ca52e"],[]]},{"id":"ddd64464.ca52e","type":"deconz-output","z":"ba820b55.5a5b68","g":"c4b69ca4.39948","name":"Blume Lamp Out","server":"ba7b33c4.06a39","device":"bc:33:ac:ff:fe:2b:a1:8c-01","device_name":"Color light 19 : Color light","command":"homekit","commandType":"homekit","payload":"payload","payloadType":"msg","transitionTime":"","x":710,"y":680,"wires":[]},{"id":"8140d8f9.95c11","type":"homekit-bridge","z":"","bridgeName":"Pandora","pinCode":"201-90-222","port":"","allowInsecureRequest":false,"manufacturer":"NRCHKB","model":"1.2.0","serialNo":"Default Serial Number","firmwareRev":"1.2.0","hardwareRev":"1.2.0","softwareRev":"1.2.0","customMdnsConfig":false,"mdnsMulticast":true,"mdnsInterface":"","mdnsPort":"","mdnsIp":"","mdnsTtl":"","mdnsLoopback":true,"mdnsReuseAddr":true,"allowMessagePassthrough":false},{"id":"ba7b33c4.06a39","type":"deconz-server","z":"","name":"Phoscon-GW","ip":"10.0.1.6","port":"80","apikey":"xxxxxxxx","ws_port":"443","secure":false,"polling":"15"}]

** Screens / Logs **

** Hardware / Software **
  - raspberry 3B   
  - version of deconz gateway: [2.05.86 / 9/14/2020] 
  - version of node-red-contrib-deconz: [1.2.0]

**Comment by Einstein2150** [comment]
This is a firmware-issue of nearly almost ikea-lights. You can try to set the `transitionTime` to `0`.

**Comment by TheNON75** [comment]
Thanks for the hint. The transition time is 0 already, still not okay. Does your accept Hue?

**Comment by Einstein2150** [comment]
Try to split the commands. One for the color and one for the hue. You have to add a little delay around 100ms between the two commands. The actual firmware can't manage more than one command while the first command is still in transition. Without sending a explicit transition of 0 to the gateway or splitting the commands the default transition of 0.4 kills the second command.

**Comment by TheNON75** [comment]
Thank you, I will try sending it async.
For your info, according to the opening comment, I’ve tried with a single hue payload too, but without success, tho it should have had some effect on it.

**Comment by Zehir** [comment]
Issue solved, check #99 for output
