### ISSUE TITLE
Out node: homekit type msg not working in all cases

### ISSUE THREAD

**Issue by TheNON75** [Mimiix/node-red-contrib-deconz#96]
** Describe issue **
The deconz out nodes are set to expect homekit payload type, which works if the payload is coming from a homekit node.
In case I would like to send a payload of this type from a function node, the deconz out node ignores the payload and nothing happens. The reason for trying this is, that I would like to avoid using duplicate out nodes for the same accessory.

I appreciate the help in advance

** Your flow here **
msg example: 
{"_msgid":"be80185.0e22ae8","payload":{"Saturation":92,"Hue":42,"Brightness":100,"On":true},"topic":"light","hap":{},"name":"Bed Light"}

** Screens / Logs **

** Hardware / Software **
  - raspberry 3B   
  - version of deconz gateway: [2.05.86 / 9/14/2020] 
  - version of node-red-contrib-deconz: [1.2.0]

**Comment by andreypopov** [comment]
show OUT node settings

**Comment by Zehir** [comment]
The HomeKit is looking for the presence a `context` value in `msg.hap` but you can use the command of type object json to send multiple commands.

**Comment by TheNON75** [comment]
Hi @Zehir,

thanks for the information.
the HomeKit node itself works well.
i meant the deconz out node if set to operate with “HomeKit” message type and I send a generated payload from a function node. As you can see in the example, msg.hap is defined as an object in the message.

the out node is receiving payloads both from HomeKit node (no issues here) and from a func node (wireless dimmer). I have issues with the latter one

**Comment by Zehir** [comment]
Hap is empty in your example, try using hap:{context:true}

**Comment by TheNON75** [comment]
Thanks, @Zehir,

indeed this was the solution
